### ISSUE TITLE
Support for TinyMCE 6?

### ISSUE THREAD

**Issue by sweh** [plone/plone.protect#106]
Hi there,

are there any plans to support TinyMCE 6? In TnyMCE 6 the `window.tinymce.util.XHR` object was removed [1]. We access it in protect.js line 32 which fails with an 

```
Uncaught TypeError: Cannot read properties of undefined (reading '_send')
    at ++resource++protect.js:32:48
```

[1] https://www.tiny.cloud/docs/api/tinymce.util/tinymce.util.xhr/

**Comment by petschki** [comment]
Plone 6.1 comes with the latest TinyMCE 7 ... I've fixed that in #118
