### ISSUE TITLE
ProtectTransform gives warning when trying and failing to parse response with empty body

### ISSUE THREAD

**Issue by datakurre** [plone/plone.protect#15]
If response is a stream iterator with `text/html` content type plone.protect tries to parse it even its response.body is an empty string. (A special case with stream iterator responses.)

```
2015-09-04 20:19:51 WARNING plone.protect error parsing dom, failure to add csrf token to response for url http://localhost:8080/Plone/sample-folder/copy_of_front-page/++contentlayout++default/document.html
```

Maybe plone.protect should check and not parse if not result (allow it to be empty string).

**Comment by mauritsvanrees** [comment]
Is this still a problem? How can we reproduce this?

plone.protect has had several releases lately, which may have fixed this. I have just released 3.0.16. See the versions list on the hotfix page:
https://plone.org/products/plone-hotfix/releases/20151006

**Comment by datakurre** [comment]
This was seen with Mosaic, when rendering a mosaic view. @vangheem @agitator ?

**Comment by laulaz** [comment]
For the record, this hasn't change in ```plone.protect = 3.0.20``` & ```plone4.csrffixes = 1.1```.
