### ISSUE TITLE
How to display within an iframe?

### ISSUE THREAD

**Issue by spanish** [plone/plone.protect#28]
Hello,

I need display a Plone 4 site within an iframe.

Please, how coul I do this with plone.protect 3.0.0 or higuer?

Thanks!

Manuel

**Comment by vangheem** [comment]
Check the documentation on the ``PLONE_X_FRAME_OPTIONS`` environment variable: https://pypi.python.org/pypi/plone.protect

Or override the ``X-Frame-Options`` header on your proxy server.

Remember, this opens you up to clickjacking attempts potentially.

**Comment by vangheem** [comment]
See https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options

**Comment by spanish** [comment]
Thanks, Nathan.

I know the risk and I don't like this, but I can't avoid it currently (it's not my decision).

At least, using PLONE_X_FRAME_OPTIONS ALLOW-FROM http://domain.tld, I can limit the vulnerability to a single domain.

Regards,

Manuel
