### ISSUE TITLE
confirm-action page not found on subsite

### ISSUE THREAD

**Issue by ivanteoh** [plone/plone.protect#51]
# Problem

`This page does not seem to exist...` when http://subsite/@@confirm-action?original_url=http%3A%2F%2F... is loaded

https://github.com/plone/plone.protect/blob/master/plone/protect/configure.zcml#L43-L49

Any reason that the page has to only for `Products.CMFPlone.interfaces.IPloneSiteRoot`? Why `*` can't be used?

**Comment by vangheem** [comment]
AFAIK, no reason "*" can't be used.
