### ISSUE TITLE
plone.protect prevents the execution of PythonScripts in the ZMI root

### ISSUE THREAD

**Issue by zopyx** [plone/plone.protect#6]
Plone 5. PythonScripts in the Zope root can no longer be executed because of plone.protect. All transactions will be aborted:

plone.protect aborting transaction due to no CSRF protection on url http://localhost:8083/copy_master

This new behavior was introduced with Plone 5, all scripts are working in Plone 4.3.
This is a major backward compatibility foul.

**Comment by vangheem** [comment]
I can not reproduce this. Scripts work fine for me.

Are you doing writes to the database in the scripts? If you are, then it's a security problem if you are not running them in a way that provides the CSRF token.

Please provide more info and re-open if something else is happening.
