### ISSUE TITLE
Changing admin password is impossible

### ISSUE THREAD

**Issue by MichaelHierweck** [plone/plone.protect#9]
The CSRF protection breaks the possibility to change the admin password inside the ZMI.
<pre>
Site Error

An error was encountered while publishing this resource.

Error Type: Forbidden
Error Value: incorrect CSRF token

Troubleshooting Suggestions

    The URL may be incorrect.
    The parameters passed to this resource may be incorrect.
    A resource that this resource relies on may be encountering an error.

For more detailed information about the error, please refer to the error log.

If the error persists please contact the site maintainer. Thank you for your patience. </pre>

**Comment by davisagli** [comment]
I believe this was already fixed: https://github.com/plone/plone.protect/commit/a3e5de84425c538288afb7ded02ee4748cb60adb
